// Pragmatic Play game symbols for free-play demo embedding
// Maps game slugs to Pragmatic Play gameSymbol parameter values

export const pragmaticPlaySymbols = {
  "gates-of-olympus": "vs20olympgate",
  "sweet-bonanza": "vs40sweetbonanza",
  "wolf-gold": "vs25wolfgold",
  "big-bass-bonanza": "vs20fishin",
  "starlight-princess": "vs20starlight",
  "the-dog-house": "vs40doghouse",
  "dog-house-megaways": "vs25doghousemw",
  "fruit-party": "vs40fruitparty",
  "chilli-heat": "vs25chillimet",
  "john-hunter": "vs20bookoftut",
  "curse-of-the-werewolf": "vs20werewolf",
  "madame-destiny": "vs20mmedestiny",
  "power-of-torii": "vs30torii",
  "the-greatest-catch": "vs20fishin2",
  "big-bass-splash": "vs20ffishin",
  "big-bass-bonanza-megaways": "vs25megafish",
  "5-dragons": "vs40dragons",
  "golden-tale": "vs20goldtale",
  "razor-returns": "vs30razorret",
  "wild-west-gold": "vs20westgold",
  "fire-strike": "vs20firestrike",
  "pirates-pots": "vs30pirate",
  "888-dragons": "vs30dragons3",
  "joker-jewels": "vs10jokerjewels",
  "book-of-golden-sands": "vs30bookofgold",
  "buffalo-king": "vs30buffalo",
  "caishang-cash-pots": "vs30cashpot",
  "bison-x": "vs40bisonx",
  "demon-pots": "vs30demonpot",
  "dragon-tiger": "vs10dragontiger",
  "fortune-pots": "vs40fortune",
  "ganesh-fortune": "vs30ganesh",
  "gates-of-tartarus": "vs30tartarus",
  "heist-stake": "vs30heist",
  "leprechaun-song": "vs40leprechaun",
  "muertos-multiplier": "vs20muertos",
  "night-of-the-living-tread": "vs30tread",
  "panda-fortune": "vs30panda",
  "pirate-silver": "vs20pirates2",
  "power-of-minotaurus": "vs20minotaur",
  "ring-of-odins-wild": "vs25odinswild",
  "rise-of-samurai": "vs30samurai3",
  "rise-of-samurai-4": "vs30samurai4",
  "snake-eye": "vs20snakeeye",
  "sugar-crush": "vs30sugarcrush",
  "super-joker": "vs20superjoker",
  "the-bone-riders": "vs40boneriders",
  "ultra-burn": "vs20ultraburn",
  "wild-ape": "vs30wildape",
  "7-pigs": "vs20piggy",
  "beast-of-wealth": "vs30beast",
} as const;

export type GameSlug = keyof typeof pragmaticPlaySymbols;

export const gameInfo: Record<string, {title: string; provider: string; rtp: string; volatility: string; maxWin: string; description: string}> = {
  "gates-of-olympus": { title: "Gates of Olympus", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Very High", maxWin: "5,000x", description: "Zeus-powered tumbling reels slot with increasing multipliers up to 500x in free spins." },
  "sweet-bonanza": { title: "Sweet Bonanza", provider: "Pragmatic Play", rtp: "96.48%", volatility: "High", maxWin: "21,100x", description: "Candy-themed cluster pays slot with tumbling reels and massive multiplier potential." },
  "wolf-gold": { title: "Wolf Gold", provider: "Pragmatic Play", rtp: "96.0%", volatility: "Medium", maxWin: "2,500x", description: "Nature-themed slot with 3 progressive jackpots, money respins, and free spins." },
  "big-bass-bonanza": { title: "Big Bass Bonanza", provider: "Pragmatic Play", rtp: "96.71%", volatility: "High", maxWin: "4,000x", description: "Fishing-themed money collect slot where fisherman wilds collect visible cash values." },
  "starlight-princess": { title: "Starlight Princess", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Anime-inspired tumbling reels slot with 500x multipliers and free spins." },
  "the-dog-house": { title: "The Dog House", provider: "Pragmatic Play", rtp: "96.51%", volatility: "High", maxWin: "6,750x", description: "Sticky wild multipliers up to 3x in a charming suburban dog-themed slot." },
  "dog-house-megaways": { title: "The Dog House Megaways", provider: "Pragmatic Play", rtp: "96.55%", volatility: "High", maxWin: "12,305x", description: "Megaways version with up to 117,649 ways and raining wilds or sticky wilds free spins." },
  "fruit-party": { title: "Fruit Party", provider: "Pragmatic Play", rtp: "96.47%", volatility: "High", maxWin: "5,000x", description: "Cluster pays fruit slot with random multipliers up to 256x in free spins." },
  "chilli-heat": { title: "Chilli Heat", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium", maxWin: "2,512x", description: "Mexican fiesta slot with money respin feature and 3 fixed jackpots." },
  "john-hunter": { title: "John Hunter and the Book of Tut", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,500x", description: "Expanding symbol free spins in an Egyptian adventure with the fearless explorer." },
  "curse-of-the-werewolf": { title: "Curse of the Werewolf Megaways", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "40,835x", description: "Megaways horror slot with mystery symbols and progressive free spins modifiers." },
  "madame-destiny": { title: "Madame Destiny", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "1,080x", description: "Mystical fortune teller slot with 2x wild multipliers and retriggerable free spins." },
  "power-of-torii": { title: "Power of Torii", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Japanese-themed slot with expanding wilds and Torii gate respin features." },
  "the-greatest-catch": { title: "Big Bass Bonanza: Keeping It Reel", provider: "Pragmatic Play", rtp: "96.71%", volatility: "High", maxWin: "10,000x", description: "Enhanced fishing sequel with fish cash symbols and golden wild collectors." },
  "big-bass-splash": { title: "Big Bass Splash", provider: "Pragmatic Play", rtp: "96.71%", volatility: "High", maxWin: "5,000x", description: "Big Bass variant with extra fisherman wilds and truck upgrade modifiers." },
  "big-bass-bonanza-megaways": { title: "Big Bass Bonanza Megaways", provider: "Pragmatic Play", rtp: "96.7%", volatility: "High", maxWin: "5,040x", description: "Megaways fishing action with up to 46,656 ways and money collect mechanics." },
  "5-dragons": { title: "5 Dragons", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Asian dragon slot with multiple free spin options and wild multiplier choices." },
  "golden-tale": { title: "Golden Tale", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium", maxWin: "2,500x", description: "Enchanted forest adventure with golden book free spins and expanding symbols." },
  "razor-returns": { title: "Razor Returns", provider: "Push Gaming", rtp: "96.24%", volatility: "High", maxWin: "100,000x", description: "Shark-infested underwater slot with mystery stacks and razor reveal feature." },
  "wild-west-gold": { title: "Wild West Gold", provider: "Pragmatic Play", rtp: "96.51%", volatility: "High", maxWin: "10,000x", description: "Cowboy-themed slot with sticky wild multipliers up to 5x in free spins." },
  "fire-strike": { title: "Fire Strike", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium-High", maxWin: "2,500x", description: "Classic fire and dice slot with strike respins and jackpot prizes." },
  "pirates-pots": { title: "Pirate's Pots", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Swashbuckling pirate adventure with treasure chest collect features." },
  "888-dragons": { title: "888 Dragons", provider: "Pragmatic Play", rtp: "96.84%", volatility: "Low-Medium", maxWin: "1,000x", description: "Minimalist 3-reel Asian dragon slot with simple classic gameplay." },
  "joker-jewels": { title: "Joker's Jewels", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium", maxWin: "1,040x", description: "Classic joker-themed slot with straightforward 5-line action." },
  "book-of-golden-sands": { title: "Book of Golden Sands", provider: "Pragmatic Play", rtp: "96.46%", volatility: "High", maxWin: "10,000x", description: "Egyptian book slot with expanding symbol wilds and 6 reels for extra ways." },
  "buffalo-king": { title: "Buffalo King", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "American prairie wildlife slot with 4,096 ways and stacked buffalo symbols." },
  "caishang-cash-pots": { title: "Caishen's Cash Pots", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium", maxWin: "2,500x", description: "Chinese wealth god slot with cash pot collect and fortune respins." },
  "bison-x": { title: "Bison X", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Bison-themed wilderness slot with stampede mechanics and expanding reels." },
  "demon-pots": { title: "Demon Pots", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "10,000x", description: "Dark fantasy slot with pot collection features and demon wild modifiers." },
  "dragon-tiger": { title: "Dragon Tiger", provider: "Pragmatic Play", rtp: "96.53%", volatility: "Low-Medium", maxWin: "18,125x", description: "Asian 3-reel slot with dragon and tiger symbols and big line pays." },
  "fortune-pots": { title: "Fortune Pots", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium", maxWin: "2,500x", description: "Lucky charm slot with pot collection and fortune wheel bonus." },
  "ganesh-fortune": { title: "Ganesha Fortune", provider: "PG Soft", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Hindu deity-themed slot with expanding wilds and free spin multipliers." },
  "gates-of-tartarus": { title: "Gates of Tartarus", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Very High", maxWin: "15,000x", description: "Underworld-themed tumbling reels slot with increasing dark multipliers." },
  "heist-stake": { title: "Heist Stake", provider: "Pragmatic Play", rtp: "96.51%", volatility: "High", maxWin: "10,000x", description: "Bank robbery themed slot with vault collect and getaway chase features." },
  "leprechaun-song": { title: "Leprechaun Song", provider: "Pragmatic Play", rtp: "96.46%", volatility: "Medium", maxWin: "6,040x", description: "Irish luck slot with rainbow free spins, pick-a-fiddle, and coin collector." },
  "muertos-multiplier": { title: "Muertos Multiplier Megaways", provider: "Pragmatic Play", rtp: "96.03%", volatility: "High", maxWin: "10,000x", description: "Day of the Dead Megaways with cascading wins and increasing multipliers." },
  "night-of-the-living-tread": { title: "Night of the Living Tread", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "10,000x", description: "Zombie horror slot with tread collect features and survival free spins." },
  "panda-fortune": { title: "Panda Fortune", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Cute panda-themed Asian slot with bamboo wilds and fortune free spins." },
  "pirate-silver": { title: "Pirate Silver", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "10,000x", description: "High seas treasure hunt with silver coin collect and pirate ship features." },
  "power-of-minotaurus": { title: "Power of Minotaurus", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Greek mythology slot with labyrinth features and minotaur wild charges." },
  "ring-of-odins-wild": { title: "Ring of Odin's Wild", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "7,500x", description: "Norse mythology slot with Odin wild rings and druidic free spins." },
  "rise-of-samurai": { title: "Rise of Samurai", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "25,000x", description: "Feudal Japan slot with warrior free spins and expanding battlefield reels." },
  "rise-of-samurai-4": { title: "Rise of Samurai 4", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "10,000x", description: "Latest samurai sequel with upgraded graphics and enhanced multiplier features." },
  "snake-eye": { title: "Snake Eye", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium-High", maxWin: "2,500x", description: "Dice and snake themed slot with eye wilds and slithering respins." },
  "sugar-crush": { title: "Sugar Crush", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "1,000x", description: "Sweet candy crush style slot with cluster pays and sugar rush multipliers." },
  "super-joker": { title: "Super Joker", provider: "Pragmatic Play", rtp: "96.5%", volatility: "Medium", maxWin: "1,500x", description: "Classic 3-reel joker slot with respin until you win and mystery prizes." },
  "the-bone-riders": { title: "The Bone Riders", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "10,000x", description: "Skeleton biker gang slot with bone collect and highway free spins." },
  "ultra-burn": { title: "Ultra Burn", provider: "Pragmatic Play", rtp: "96.62%", volatility: "Low-Medium", maxWin: "1,312x", description: "Fast-paced 3-reel classic slot with flaming symbols and quick spins." },
  "wild-ape": { title: "Wild Ape", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "5,000x", description: "Jungle gorilla slot with ape wilds and cascading vine features." },
  "7-pigs": { title: "7 Pigs", provider: "Pragmatic Play", rtp: "96.5%", volatility: "High", maxWin: "7,290x", description: "Farmyard fun with 7 lucky pigs, mud wilds, and barnyard bonus rounds." },
  "beast-of-wealth": { title: "Beast of Wealth", provider: "Play'n GO", rtp: "96.49%", volatility: "High", maxWin: "10,000x", description: "Asian mythical beasts slot with progressive jackpot free spin options." },
};

// Build demo embed URL
export function getDemoUrl(slug: GameSlug): string {
  const symbol = pragmaticPlaySymbols[slug];
  if (!symbol) return "";
  return `https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=${symbol}&jurisdiction=99&cur=USD&lang=en`;
}
